# toy model script
# implementing model for:
# t = 20 years
# n x m = 100 x 100 pixels = 10,000 pixels = 9,000,000 m2 (9 km2)

# states
# 1 = Undisturbed
# 2 = Degraded
# 3 = Deforested
# 4 = Regrown



############################################################
#### Dependencies and directory setup ####
#
#
library(terra)
library(glue)
library(ggplot2)
library(reshape2)
library(dplyr)

# setwd()


############################################################
#### Set parameters ####
#
#
tf <- 30 # total number of timesteps
n <- 10 # map height. set to 10 to run fast while editing. 
m <- 10 # map width

h0 <- 157 # initial human population of congo basin in millions. based on WWF which is based on CIA data sob. we can find better estimates later.
hpg <- 0.02 # human population growth rate. GENERATED BY COPILOT based on World Bank data for DRC, which is the largest country in the basin and has the most deforestation. ok this number was gend by copilot
kappa <- (1.5 / 74) # this is the climate change constant. calculated as:
# 1.5 degrees C warming between 2026 and 2100, / 74 years to estimate per-year
# linear change. this corresponds to the Intermediate (SSP2-4.5) scenario, total of 2.7 degrees warming
# since pre-industrial levels. 
alpha_h <- 0.5 # human deforestation impact constant
alpha_c <- 0.05 # climate change deforestation impact constant
beta_h <- 0.2 # human degradation impact constant
beta_c <- 0.1 # climate change degradation impact constant
gamma_h <- 0.1 # human secondary deforestation impact constant
gamma_c <- 0.005 # climate change secondary deforestation impact constant
psi_h <- 0.05 # human regrowth impact constant
# gonna consolidate regrowth into one param for now

# initial natural transition states
alpha_0 <- 0
beta_0 <- 0
gamma_0 <- 0.01
psi_0 <- 0.04

#####################################################################
#### Intialize variables ####


# initialize forest raster and set initial states
r0 <- rast(nrows = n, ncols = m) #10x10 empty raster
crs(r0) <- "local" # explicitly set non-geographic CRS to avoid bleeding between edges (otherwise terra assumes the edges wrap around and form a "globe")
values(r0) <- sample(1, ncell(r0), replace = TRUE) #fill raster w all undisturbed forest
r0[1] <- 3 #start with one deforested cell in the top left corner

levels(r0) <- data.frame( # this MUST be called AFTER setting all the raster values. raster metadata gets stripped when setting new values
  ID = 1:4,
  State = c("Undisturbed", "Degraded", "Deforested", "Regrown")
)

# number of protected cells (1% of total)
n_protected <- ceiling(0.01 * ncell(r0))

# create mask raster
protected_mask <- rast(r0)  
values(protected_mask) <- 0

# get row and column of each cell
rc <- rowColFromCell(r0, 1:ncell(r0))  # returns matrix: column 1 = row, column 2 = col

n_rows <- nrow(r0)
n_cols <- ncol(r0)

# select cells in lower-right corner
# lower rows = higher row numbers, rightmost columns = higher column numbers
lower_rows <- (n_rows - ceiling(sqrt(n_protected)) + 1):n_rows
right_cols <- (n_cols - ceiling(sqrt(n_protected)) + 1):n_cols

# find cells that match both row and column
protected_cells <- which(rc[,1] %in% lower_rows & rc[,2] %in% right_cols)

# if more cells than n_protected, keep only the first n_protected
protected_cells <- protected_cells[1:n_protected]

# set protected cells to 1
values(protected_mask)[protected_cells] <- 1

# thinking these probabilities can be thought of as "natural" transitions between states without human/climate impact? might be wrong
ug <- beta_0 
uf <- alpha_0 
ur <- 0
uu <- 1 - ug - uf - ur
gu <- 0
gf <- gamma_0
gr <- psi_0
gg <- 1 - gu - gf - gr
fu <- 0
fg <- psi_0
fr <- 0
ff <- 1 - fg - fu - fr
ru <- 0
rg <- beta_0
rf <- alpha_0
rr <- 1 - ru - rg - rf

P <- matrix( #row = current state, col = next state
  c( # U  G     F     R (to)
    uu,     ug,      uf,     ur,   # U (from)
    gu,     gg,      gf,     gr,   # G
    fu,     fg,      ff,     fr,   # F         # 0 prob of going from F -> R, change this later if we want F -> R possibility
    ru,     rg,      rf,     rr    # R 
  ),
  nrow = 4,
  byrow = TRUE
)

w <- matrix(1, 3, 3) #create a 3x3 neighborhood weight matrix
w[2, 2] <- 0



##############################################################
#### Define funcs ####
#
#
neighbor_frac <- function(r, state) {
  # Count matching neighbors
  n_match <- focal(r == state, w, sum, na.rm = TRUE, pad = TRUE, fillvalue = NA)
  # Count total existing neighbors (not NA)
  n_total <- focal(!is.na(r), w, sum, na.rm = TRUE, pad = TRUE)
  
  return(n_match / n_total)
}

modify_P <- function(P, u_frac, g_frac, f_frac, r_frac, p_frac, alpha, beta, gamma, psi) { #update p matrix based on spatial fracs and time-dependent params
  P2 <- P
  #P2[3, 3] <- P2[3, 3] + 0.3 * f_frac #3,3 is prob of going from F to F. increases depending on f_frac
  P2[1,3]  <- P2[1, 3] + alpha * (f_frac + g_frac) #1,3 is prob of going from U to F. increases depending on f_frac
  P2[1, 2] <- P2[1, 2] + beta * (g_frac + f_frac - p_frac) #1,2 is prob of going from U to G. dependence on f = edge effects
  P2[2, 3] <- P2[2, 3] + gamma * f_frac #2,3 is prob of going from G to F. increases depending on f_frac
  P2[3, 2] <- P2[3, 2] + psi * (u_frac + r_frac + g_frac) #3,2 is prob of going from F to G. increases depending on u and r and g frac
  P2[2, 4] <- P2[2, 4] + psi * (u_frac + r_frac + p_frac) #2,4 is prob of going from G to R. increases depending on u and r frac
  
  # protected effects promote regrowth & stability

  # increase regrowth along protected edges (f -> r)
  P2[3, 4] <- P2[3, 4] + p_frac

  # f → g (think of as pre-regrowth)
  P2[3, 2] <- P2[3, 2] + p_frac

  # g → r 
  P2[2, 4] <- P2[2, 4] + p_frac


  ## undisturbed forest less likely to degrade/deforest
  P2[1, 2] <- P2[1, 2] - p_frac  # U → G reduced
  P2[1, 3] <- P2[1, 3] - p_frac  # U → F reduced

  # keep probabilities non-negative
  P2[P2 < 0] <- 0
  
  row_sums <- rowSums(P2)

  # avoid division by zero, if row sum = 0, restore original P row
  zero_rows <- which(row_sums == 0)
  if (length(zero_rows) > 0) P2[zero_rows, ] <- P[zero_rows, ]

  # normalize
  P2 <- sweep(P2, 1, rowSums(P2), "/")

  return(P2)
#   P2[3, ] <- P2[3, ] / sum(P2[3, ]) # rescale all transitions from F so they sum to 1
#   P2[2, ] <- P2[2, ] / sum(P2[2, ]) # rescale all transitions from G so they sum to 1
#   P2[1, ] <- P2[1, ] / sum(P2[1, ]) # rescale all transitions from U so they sum to 1
#   P2
}

step_forest <- function(r, alpha, beta, gamma, psi) {
  
  r_new <- r  # initialize new raster
  
  # calculate neighborhood fractions once
  mf <- neighbor_frac(r, 3) # deforested neighbors
  mg <- neighbor_frac(r, 2) # degraded neighbors
  mu <- neighbor_frac(r, 1) # undisturbed neighbors
  mr <- 1 - mf - mg - mu
  mp <- neighbor_frac(protected_mask, 1) # protected neighbors
  
  # loop through each cell
  for (i in 1:ncell(r)) {
    
    # protected area → force Undisturbed
    if (values(protected_mask)[i] == 1) {
      values(r_new)[i] <- 1
      next  # skip to next cell
    }
    
    # current state
    s <- values(r)[i]
    
    # get modified transition probabilities
    Pi <- modify_P(P,
                   values(mu)[i], values(mg)[i], values(mf)[i], values(mr)[i],
                   values(mp)[i],  # p_frac
                   alpha, beta, gamma, psi)[s, ]
    
    # sample new state
    values(r_new)[i] <- sample(1:4, 1, prob = Pi)
  }
  
  return(r_new)
}



##################################################################
#### Setup graph labels ####
#
#

forest_cols <- c(
  "#6A9C52",  # 1 = Undisturbed (dark green)
  "#D96900",  # 2 = Degraded (light green)
  "#AA2A0E",  # 3 = Deforested (red)
  "#5DA5D3"   # 4 = Regrown (teal)
)



######################################################################
#### Main loop ####
#
#

r <- r0

# later change width = 1800, height = 1200
png("map_t_series/toy_map_t0.png", width=800, height=800)  # open device
dev.off()
png("map_t_series/toy_map_live.png", width=800, height=800)  # open device
terra::plot(
  r0,
  col = forest_cols,
  type = "classes",
  all_levels = TRUE, 
  main = "Timestep 0",
  axes = FALSE
)
dev.off()     

#store values for plotting
h_values <- c()
alpha_values <- c()
beta_values <- c()
gamma_values <- c()
psi_values <- c()

# track % of cells in each state 
state_perc <- data.frame(
  timestep = 0:tf,
  Undisturbed = NA,
  Degraded = NA,
  Deforested = NA,
  Regrown = NA
)

total_cells <- n * m


for (t in 0:tf) {
  cat("Simulating timestep", t, "...\n")

  # calculate time-dependent params based on constants
  h <- (h0 + hpg * t) / h0 # current population relative to initial population.
  alpha <- alpha_h * h + alpha_c * kappa * t
  beta <- beta_h * h + beta_c * kappa * t
  gamma <- gamma_h * h + gamma_c * kappa * t
  psi <- psi_h * h

  # store values for plotting
  h_values <- c(h_values, h)
  alpha_values <- c(alpha_values, alpha)    
  beta_values <- c(beta_values, beta)
  gamma_values <- c(gamma_values, gamma)
  psi_values <- c(psi_values, psi)

  if (t == 0) {
  r <- r0
  } else {
  r <- step_forest(r, alpha, beta, gamma, psi)
  }
  # Ensure levels persist, take this out later
  levels(r) <- levels(r0) # might slow stuff down
  
  # Save the timestamped file
  png(glue("map_t_series/toy_map_t{t}.png"), width=800, height=800)
  terra::plot(r, col = forest_cols, type = "classes", all_levels = TRUE, 
              main = glue("Timestep {t}"), axes = FALSE)
  dev.off()
  
  # Save the "live" (latest) file separately
  png("toy_map_live.png", width=800, height=800)
  terra::plot(r, col = forest_cols, type = "classes", all_levels = TRUE, 
              main = glue("Timestep {t}"), axes = FALSE)
  dev.off()

  # Save the timestamped file
png(glue("map_t_series/toy_map_t{t}.png"), width=800, height=800)
terra::plot(r, col = forest_cols, type = "classes", all_levels = TRUE, 
            main = glue("Timestep {t}"), axes = FALSE)
dev.off()

# Save the "live" map separately
png("toy_map_live.png", width=800, height=800)
terra::plot(r, col = forest_cols, type = "classes", all_levels = TRUE, 
            main = glue("Timestep {t}"), axes = FALSE)
dev.off()

# compute % of cells in each state
tab <- table(values(r))

state_perc$Undisturbed[t + 1] <- 100 * ifelse(!is.na(tab["1"]), tab["1"], 0) / total_cells
state_perc$Degraded[t + 1]     <- 100 * ifelse(!is.na(tab["2"]), tab["2"], 0) / total_cells
state_perc$Deforested[t + 1]   <- 100 * ifelse(!is.na(tab["3"]), tab["3"], 0) / total_cells
state_perc$Regrown[t + 1]      <- 100 * ifelse(!is.na(tab["4"]), tab["4"], 0) / total_cells
}


# Convert data to long format
df_long <- melt(state_perc, id.vars = "timestep",
                variable.name = "State",
                value.name = "Percent")

# Save larger PNG
png("forest_state_percent_timeseries.png", width = 1800, height = 1200)

ggplot(df_long, aes(x = timestep, y = Percent, color = State)) +
  geom_line(size = 1.5) +
  scale_color_manual(values = c(
    Undisturbed = "#6A9C52",
    Degraded    = "#D96900",
    Deforested  = "#AA2A0E",
    Regrown     = "#5DA5D3"
  )) +
  labs(
    title = "Forest State Distribution Over Time",
    x = "Timestep",
    y = "Percent of Landscape (%)",
    color = "Forest State"
  ) +
  theme_minimal(base_size = 16) +  # base font size
  theme(
    plot.title = element_text(size = 30, face = "bold"),  # larger title
    axis.title = element_text(size = 24, face = "bold"),  # larger axis labels
    axis.text  = element_text(size = 20),                 # larger tick labels
    legend.title = element_text(size = 22, face = "bold"),# larger legend title
    legend.text  = element_text(size = 20)               # larger legend labels
  )

dev.off()

# later change width = 1800, height = 1200

t_vector <- 0:tf

# human Population Growth
df_pop <- data.frame(
  timestep = t_vector,
  population = h_values
)

p_pop <- ggplot(df_pop, aes(x = timestep, y = population)) +
  geom_line() +
  geom_point() +
  theme_minimal() +
  labs(
    title = "Human Population Growth",
    x = "Timestep",
    y = "Relative Population"
  )

ggsave("param_figs/human_population_growth.png", p_pop, width = 8, height = 6)

# alpha (U->F)
df_alpha <- data.frame(
  timestep = t_vector,
  alpha = alpha_values
)

p_alpha <- ggplot(df_alpha, aes(x = timestep, y = alpha)) +
  geom_line() +
  geom_point() +
  theme_minimal() +
  labs(
    title = "Undisturbed to Deforested (Alpha)",
    x = "Timestep",
    y = "Alpha Value"
  )

ggsave("param_figs/alpha_values.png", p_alpha, width = 8, height = 6)

# beta (U->G)
df_beta <- data.frame(
  timestep = t_vector,
  beta = beta_values
)

p_beta <- ggplot(df_beta, aes(x = timestep, y = beta)) +
  geom_line() +
  geom_point() +
  theme_minimal() +
  labs(
    title = "Undisturbed to Degraded (Beta)",
    x = "Timestep",
    y = "Beta Value"
  )

ggsave("param_figs/beta_values.png", p_beta, width = 8, height = 6)

# gamma (G->F)
df_gamma <- data.frame(
  timestep = t_vector,
  gamma = gamma_values
)

p_gamma <- ggplot(df_gamma, aes(x = timestep, y = gamma)) +
  geom_line() +
  geom_point() +
  theme_minimal() +
  labs(
    title = "Degraded to Deforested (Gamma)",
    x = "Timestep",
    y = "Gamma Value"
  )

ggsave("param_figs/gamma_values.png", p_gamma, width = 8, height = 6)

# psi (F->R)
df_psi <- data.frame(
  timestep = t_vector,
  psi = psi_values
)

p_psi <- ggplot(df_psi, aes(x = timestep, y = psi)) +
  geom_line() +
  geom_point() +
  theme_minimal() +
  labs(
    title = "Deforested to Regrowth (Psi)",
    x = "Timestep",
    y = "Psi Value"
  )

ggsave("param_figs/psi_values.png", p_psi, width = 8, height = 6)




